import { ParamGroup } from './params';

export interface ParamSpec {
    group: ParamGroup;
    key: string;
    label: string;
    hint: string;
    kind: 'range' | 'toggle' | 'choice';
    min?: number;
    max?: number;
    step?: number;
    options?: readonly string[];
    restage: 'detect' | 'match' | 'model' | 'global' | 'compose';
    advanced?: boolean;
}

export const PARAM_SPECS: readonly ParamSpec[] = [
    {
        group: 'detect',
        key: 'detector',
        label: 'Detector',
        hint: 'Harris e Shi-Tomasi usam a matriz de autocorrelação; FAST usa teste de segmento',
        kind: 'choice',
        options: ['harris', 'shi-tomasi', 'fast'],
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'workWidth',
        label: 'Resolução',
        hint: 'Largura em px usada para detectar e casar características',
        kind: 'range',
        min: 320,
        max: 1280,
        step: 32,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'derivativeSigma',
        label: 'σ derivada',
        hint: 'Suaviza antes de derivar (controla o ruído dos gradientes)',
        kind: 'range',
        min: 0.5,
        max: 3,
        step: 0.1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'integrationSigma',
        label: 'σ integração',
        hint: 'Janela que soma os produtos das derivadas em A (use σi > σd)',
        kind: 'range',
        min: 0.8,
        max: 6,
        step: 0.1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'harrisAlpha',
        label: 'α de Harris',
        hint: 'R = det(A) − α·tr(A)²; penaliza bordas',
        kind: 'range',
        min: 0.01,
        max: 0.12,
        step: 0.005,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'relativeThreshold',
        label: 'Limiar',
        hint: 'Fração da resposta máxima aceita como canto',
        kind: 'range',
        min: 0.0005,
        max: 0.08,
        step: 0.0005,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'nmsRadius',
        label: 'Raio NMS',
        hint: 'Supressão não-máxima: um pico por vizinhança',
        kind: 'range',
        min: 1,
        max: 16,
        step: 1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'maxKeypoints',
        label: 'Máx. pontos',
        hint: 'Teto de pontos por imagem',
        kind: 'range',
        min: 100,
        max: 3000,
        step: 50,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'adaptiveNms',
        label: 'ANMS',
        hint: 'Supressão adaptativa: pontos fortes E espalhados pela imagem',
        kind: 'toggle',
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'fastThreshold',
        label: 'Limiar FAST',
        hint: 'Diferença mínima de intensidade no arco',
        kind: 'range',
        min: 5,
        max: 60,
        step: 1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'subPixel',
        label: 'Sub-pixel',
        hint: 'Ajusta uma quadrática à resposta e toma o vértice',
        kind: 'toggle',
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'match',
        key: 'descriptorPatch',
        label: 'Patch',
        hint: 'Lado da janela do BRIEF orientado (px)',
        kind: 'range',
        min: 15,
        max: 47,
        step: 2,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'match',
        key: 'loweRatio',
        label: 'Ratio test',
        hint: 'Aceita o par se d1/d2 < limiar sobre os 2 vizinhos mais próximos',
        kind: 'range',
        min: 0.5,
        max: 0.95,
        step: 0.01,
        restage: 'match',
    },
    {
        group: 'match',
        key: 'crossCheck',
        label: 'Cruzada',
        hint: 'Exige que o casamento seja mútuo nas duas direções',
        kind: 'toggle',
        advanced: true,
        restage: 'match',
    },
    {
        group: 'model',
        key: 'model',
        label: 'Modelo',
        hint: 'Mínimo de pares = DoF/2: 1, 2, 3 ou 4',
        kind: 'choice',
        options: ['translation', 'similarity', 'affine', 'homography'],
        restage: 'model',
    },
    {
        group: 'model',
        key: 'ransacThreshold',
        label: 'Limiar RANSAC',
        hint: 'Resíduo máximo (px) para um par contar como inlier',
        kind: 'range',
        min: 0.5,
        max: 12,
        step: 0.25,
        restage: 'model',
    },
    {
        group: 'model',
        key: 'ransacConfidence',
        label: 'Confiança',
        hint: 'N = log(1−p)/log(1−wᵏ) define as tentativas adaptativas',
        kind: 'range',
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        advanced: true,
        restage: 'model',
    },
    {
        group: 'model',
        key: 'minInliers',
        label: 'Mín. inliers',
        hint: 'Abaixo disso o par é considerado sem sobreposição',
        kind: 'range',
        min: 6,
        max: 120,
        step: 1,
        advanced: true,
        restage: 'model',
    },
    {
        group: 'model',
        key: 'minInlierRatio',
        label: 'Taxa mín.',
        hint: 'Fração de inliers exigida para aceitar a geometria',
        kind: 'range',
        min: 0.05,
        max: 0.8,
        step: 0.01,
        advanced: true,
        restage: 'model',
    },
    {
        group: 'global',
        key: 'autoFocal',
        label: 'Focal auto',
        hint: 'Estima f das homografias (mediana sobre os pares)',
        kind: 'toggle',
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'bundleWindow',
        label: 'Janela',
        hint: 'Quantas câmeras recentes são otimizadas juntas',
        kind: 'range',
        min: 0,
        max: 20,
        step: 1,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'bundleIterations',
        label: 'Iterações',
        hint: 'Passos de Levenberg-Marquardt por inserção',
        kind: 'range',
        min: 0,
        max: 40,
        step: 1,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'refineFocal',
        label: 'Refinar f',
        hint: 'Trata a distância focal como parâmetro livre',
        kind: 'toggle',
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'candidateNeighbours',
        label: 'Vizinhos',
        hint: 'Quantas câmeras o índice espacial propõe por novo quadro',
        kind: 'range',
        min: 1,
        max: 12,
        step: 1,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'keyframeMinAngle',
        label: 'Ângulo mín.',
        hint: 'Graus de cobertura nova exigidos para guardar o quadro',
        kind: 'range',
        min: 0,
        max: 20,
        step: 0.5,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'compose',
        key: 'surface',
        label: 'Superfície',
        hint: 'Plano até ~90°, cilindro até 360° na horizontal, esfera 360°×180°',
        kind: 'choice',
        options: ['planar', 'cylindrical', 'spherical'],
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'canvasWidth',
        label: 'Mosaico',
        hint: 'Resolução do acumulador (memória fixa, independente do nº de fotos)',
        kind: 'range',
        min: 512,
        max: 6144,
        step: 256,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'blend',
        label: 'Mistura',
        hint: 'Média mostra fantasmas; feather suaviza; multiband preserva detalhe',
        kind: 'choice',
        options: ['average', 'feather', 'multiband'],
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'featherWidth',
        label: 'Feather',
        hint: 'Rampa alfa em px: larga suaviza, estreita preserva nitidez',
        kind: 'range',
        min: 2,
        max: 200,
        step: 2,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'bands',
        label: 'Bandas',
        hint: 'Níveis da pirâmide Laplaciana usados na mistura',
        kind: 'range',
        min: 2,
        max: 7,
        step: 1,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'seam',
        label: 'Costura',
        hint: 'Escolhe a fonte de cada pixel por caminho de custo mínimo',
        kind: 'toggle',
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'deghost',
        label: 'Deghost',
        hint: 'Onde as imagens discordam, usa uma só fonte em vez da média',
        kind: 'toggle',
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'deghostThreshold',
        label: 'Limiar deghost',
        hint: 'Diferença de intensidade que caracteriza objeto móvel',
        kind: 'range',
        min: 4,
        max: 120,
        step: 2,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'exposureCompensation',
        label: 'Exposição',
        hint: 'Ganho por imagem estimado nas sobreposições',
        kind: 'toggle',
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'gpu',
        label: 'GPU',
        hint: 'Usa WebGL2 na detecção, no casamento e na mistura quando for mais rápido',
        kind: 'toggle',
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'composeWidth',
        label: 'Fonte',
        hint: 'Largura em px com que cada foto é reprojetada no mosaico',
        kind: 'range',
        min: 320,
        max: 2048,
        step: 64,
        advanced: true,
        restage: 'compose',
    },
];
