import { ParamGroup } from './params';

export interface ParamSpec {
    group: ParamGroup;
    key: string;
    label: string;
    hint: string;
    kind: 'range' | 'toggle' | 'choice';
    min?: number;
    max?: number;
    step?: number;
    options?: readonly string[];
    restage?: 'detect' | 'match' | 'model' | 'global' | 'compose';
    advanced?: boolean;
}

export const PARAM_SPECS: readonly ParamSpec[] = [
    {
        group: 'detect',
        key: 'detector',
        label: 'Detector',
        hint: 'Harris and Shi-Tomasi use the autocorrelation matrix; FAST uses a segment test',
        kind: 'choice',
        options: ['harris', 'shi-tomasi', 'fast'],
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'workWidth',
        label: 'Resolution',
        hint: 'Width in px used to detect and match features; applies from the next panorama',
        kind: 'range',
        min: 320,
        max: 1280,
        step: 32,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'derivativeSigma',
        label: 'Derivative σ',
        hint: 'Smooths before differentiating (controls gradient noise)',
        kind: 'range',
        min: 0.5,
        max: 3,
        step: 0.1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'integrationSigma',
        label: 'Integration σ',
        hint: 'Window that sums the derivative products in A (use σi > σd)',
        kind: 'range',
        min: 0.8,
        max: 6,
        step: 0.1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'harrisAlpha',
        label: 'Harris α',
        hint: 'R = det(A) − α·tr(A)²; penalises edges',
        kind: 'range',
        min: 0.01,
        max: 0.12,
        step: 0.005,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'relativeThreshold',
        label: 'Threshold',
        hint: 'Fraction of the maximum response accepted as a corner',
        kind: 'range',
        min: 0.0005,
        max: 0.08,
        step: 0.0005,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'nmsRadius',
        label: 'NMS radius',
        hint: 'Non-maximum suppression: one peak per neighborhood',
        kind: 'range',
        min: 1,
        max: 16,
        step: 1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'maxKeypoints',
        label: 'Max points',
        hint: 'Cap on points per image',
        kind: 'range',
        min: 100,
        max: 3000,
        step: 50,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'adaptiveNms',
        label: 'ANMS',
        hint: 'Adaptive suppression: points that are strong AND spread across the image',
        kind: 'toggle',
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'fastThreshold',
        label: 'FAST threshold',
        hint: 'Minimum intensity difference along the arc',
        kind: 'range',
        min: 5,
        max: 60,
        step: 1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'subPixel',
        label: 'Sub-pixel',
        hint: 'Fits a quadratic to the response and takes its vertex',
        kind: 'toggle',
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'scaleLevels',
        label: 'Scales',
        hint: 'Pyramid levels searched for corners (1 = single scale)',
        kind: 'range',
        min: 1,
        max: 6,
        step: 1,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'detect',
        key: 'scaleFactor',
        label: 'Scale step',
        hint: 'Size ratio between consecutive pyramid levels',
        kind: 'range',
        min: 1.2,
        max: 2,
        step: 0.05,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'match',
        key: 'descriptorPatch',
        label: 'Patch',
        hint: 'Side of the oriented BRIEF window (px)',
        kind: 'range',
        min: 15,
        max: 47,
        step: 2,
        advanced: true,
        restage: 'detect',
    },
    {
        group: 'match',
        key: 'loweRatio',
        label: 'Ratio test',
        hint: 'Accepts the pair if d1/d2 < threshold over the 2 nearest neighbors',
        kind: 'range',
        min: 0.5,
        max: 0.95,
        step: 0.01,
        restage: 'match',
    },
    {
        group: 'match',
        key: 'crossCheck',
        label: 'Cross-check',
        hint: 'Requires the match to be mutual in both directions',
        kind: 'toggle',
        advanced: true,
        restage: 'match',
    },
    {
        group: 'model',
        key: 'model',
        label: 'Model',
        hint: 'Minimum pairs = DoF/2: 1, 2, 3 or 4',
        kind: 'choice',
        options: ['translation', 'similarity', 'affine', 'homography'],
        restage: 'model',
    },
    {
        group: 'model',
        key: 'ransacThreshold',
        label: 'RANSAC threshold',
        hint: 'Maximum symmetric transfer error (px) at full resolution; scaled by each keypoint pyramid scale',
        kind: 'range',
        min: 0.5,
        max: 12,
        step: 0.25,
        restage: 'model',
    },
    {
        group: 'model',
        key: 'ransacConfidence',
        label: 'Confidence',
        hint: 'N = log(1−p)/log(1−wᵏ) sets the adaptive trial count',
        kind: 'range',
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        advanced: true,
        restage: 'model',
    },
    {
        group: 'model',
        key: 'minInliers',
        label: 'Min inliers',
        hint: 'Below this the pair is considered non-overlapping',
        kind: 'range',
        min: 6,
        max: 120,
        step: 1,
        advanced: true,
        restage: 'model',
    },
    {
        group: 'model',
        key: 'minInlierRatio',
        label: 'Min ratio',
        hint: 'Inlier fraction required to accept the geometry',
        kind: 'range',
        min: 0.05,
        max: 0.8,
        step: 0.01,
        advanced: true,
        restage: 'model',
    },
    {
        group: 'global',
        key: 'autoFocal',
        label: 'Focal auto',
        hint: 'Estimates f from the homographies (median over the pairs)',
        kind: 'toggle',
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'bundleWindow',
        label: 'Window',
        hint: 'How many recent cameras are optimized together',
        kind: 'range',
        min: 0,
        max: 20,
        step: 1,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'bundleIterations',
        label: 'Iterations',
        hint: 'Levenberg-Marquardt steps per insertion',
        kind: 'range',
        min: 0,
        max: 40,
        step: 1,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'refineFocal',
        label: 'Refine f',
        hint: 'Treats the focal length as a free parameter',
        kind: 'toggle',
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'refineDistortion',
        label: 'Lens κ₁',
        hint: 'Estimates radial lens distortion d = n(1 + κ₁|n|²) and corrects it when warping',
        kind: 'toggle',
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'candidateNeighbors',
        label: 'Neighbors',
        hint: 'How many cameras the spatial index proposes per new frame',
        kind: 'range',
        min: 1,
        max: 12,
        step: 1,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'global',
        key: 'keyframeMinAngle',
        label: 'Min angle',
        hint: 'Degrees of new coverage required to keep the frame',
        kind: 'range',
        min: 0,
        max: 20,
        step: 0.5,
        advanced: true,
        restage: 'global',
    },
    {
        group: 'compose',
        key: 'surface',
        label: 'Surface',
        hint: 'Auto picks the plane while the photos fit ~100°×84°, then the cylinder (360°×92°), then the sphere',
        kind: 'choice',
        options: ['auto', 'planar', 'cylindrical', 'spherical'],
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'canvasWidth',
        label: 'Mosaic',
        hint: 'Accumulator resolution (fixed memory, independent of the number of photos)',
        kind: 'range',
        min: 512,
        max: 6144,
        step: 256,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'blend',
        label: 'Blending',
        hint: 'Average cuts hard at the seam (ghosts without seams); feather smooths; multiband preserves detail',
        kind: 'choice',
        options: ['average', 'feather', 'multiband'],
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'featherWidth',
        label: 'Feather',
        hint: 'Alpha ramp in px: wide smooths, narrow preserves sharpness',
        kind: 'range',
        min: 2,
        max: 200,
        step: 2,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'bands',
        label: 'Bands',
        hint: 'Laplacian pyramid levels used for blending',
        kind: 'range',
        min: 2,
        max: 7,
        step: 1,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'seam',
        label: 'Seams',
        hint: 'Picks the source of each pixel along a minimum-cost path',
        kind: 'toggle',
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'seamMegapixels',
        label: 'Seam detail',
        hint: 'Megapixels used to search the seam; 0 searches at full resolution',
        kind: 'range',
        min: 0,
        max: 2,
        step: 0.05,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'deghost',
        label: 'Deghost',
        hint: 'Where images disagree, uses a single source instead of the average',
        kind: 'toggle',
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'deghostThreshold',
        label: 'Deghost threshold',
        hint: 'Intensity difference that marks a moving object',
        kind: 'range',
        min: 4,
        max: 120,
        step: 2,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'exposureCompensation',
        label: 'Exposure',
        hint: 'Per-image gain estimated over the overlaps',
        kind: 'toggle',
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'blockGains',
        label: 'Block gains',
        hint: 'Also corrects brightness region by region (phone tone mapping) on top of the per-image gain',
        kind: 'toggle',
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'vignetting',
        label: 'Vignetting',
        hint: 'Estimates the radial falloff V(r) = 1 + β r² from the overlaps and removes it',
        kind: 'toggle',
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'gpu',
        label: 'GPU',
        hint: 'Uses WebGL2 for detection, matching and blending when it is faster',
        kind: 'toggle',
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'composeWidth',
        label: 'Source',
        hint: 'Width in px at which each photo is reprojected into the mosaic',
        kind: 'range',
        min: 320,
        max: 4096,
        step: 64,
        advanced: true,
        restage: 'compose',
    },
    {
        group: 'compose',
        key: 'exportScale',
        label: 'Export scale',
        hint: 'Export resolution as a fraction of the native sampling of the photos',
        kind: 'range',
        min: 0.25,
        max: 2,
        step: 0.05,
        advanced: true,
    },
    {
        group: 'compose',
        key: 'exportMegapixels',
        label: 'Export cap',
        hint: 'Upper bound in megapixels for the export; it is rendered in tiles and streamed, so this only limits the file size',
        kind: 'range',
        min: 1,
        max: 400,
        step: 1,
        advanced: true,
    },
];
